package eu.epitech;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import java.util.ArrayList;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ActionView extends VerticalLayout implements View {
        private ArrayList<Button> actionsButton = new ArrayList<Button>();

    public ActionView() {
        setSizeFull();
        setSpacing(true);
        for (int i = 0; i < 10; ++i) {
            actionsButton.add(actionButton("Description"));
        }
        for (Button button : actionsButton) {
            addComponent(button);
        }
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
        Notification.show("Welcome to action page !");
    }

    private Button actionButton(String txt) {
        Button button = new Button(txt, new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                getUI().getNavigator().navigateTo("reaction" + "/" + txt);
            }
        });
        return button;
    }
}
