package eu.epitech;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;

import java.util.ArrayList;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReactionView extends AbsoluteLayout implements View {
    private ArrayList<Button> reactionsButton = new ArrayList<Button>();
    private String titleAction;

    public ReactionView() {
        setSizeFull();
        setWidth("2000px");
        setHeight("2000px");
        int high = 50;
        for (int i = 0; i < 5; ++i)
        {
            reactionsButton.add(reactionButton("Inhuman reaction"));
        }
        for (Button button : reactionsButton) {
            addComponent(button, "top: " + Integer.toString(high) + "px; left: 1500px;");
            high += 100;
        }
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
        if (event.getParameters() != null)
        {
            titleAction = event.getParameters();
            addComponent(actionButton(titleAction), "top: 50px; left: 50px;");
        }
        Notification.show("Welcome to Reaction Page :)");
    }

    private Button actionButton(String txt) {
        Button button = new Button(txt, new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                Notification.show("Please select a valid reaction !");
            }
        });

        button.setWidth(Integer.toString((getUI().getPage().getBrowserWindowWidth()) / 2));
        button.setHeight(Integer.toString((getUI().getPage().getBrowserWindowHeight()) / 2));
        button.setResponsive(true);
        return button;
    }

    private Button reactionButton(String txt) {
        Button button = new Button(txt, new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
              getUI().getNavigator().navigateTo("config" + "/" + titleAction + "-" + txt);
            }
        });
        return button;
    }
}
