CREATE DATABASE IF NOT EXISTS area;
GRANT USAGE ON *.* TO 'area'@'%' IDENTIFIED BY 'djh7.HDi5332jczj';
GRANT ALL PRIVILEGES ON area.* TO 'area'@'%';
FLUSH PRIVILEGES;
CREATE TABLE `area`.`action` ( `id` INT NOT NULL AUTO_INCREMENT , `fk_action_area` INT NOT NULL , `api_name` TEXT NOT NULL , `name` TEXT NOT NULL , `description` TEXT NOT NULL , `config` TEXT NULL DEFAULT NULL , `previous_state` TEXT NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `area`.`area` ( `id` INT NOT NULL AUTO_INCREMENT , `fk_area_user` INT NOT NULL , `name` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `area`.`reaction` ( `id` INT NOT NULL AUTO_INCREMENT , `fk_reaction_area` INT NOT NULL , `api_name` TEXT NOT NULL , `name` TEXT NOT NULL , `description` TEXT NOT NULL , `config` TEXT NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `area`.`token` ( `id` INT NOT NULL AUTO_INCREMENT , `fk_token_user` INT NOT NULL , `api_name` TEXT NOT NULL , `value` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `area`.`user` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT NOT NULL , `password` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `area`.`action` ADD FOREIGN KEY (`fk_action_area`) REFERENCES `area`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `area`.`area` ADD FOREIGN KEY (`fk_area_user`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `area`.`reaction` ADD FOREIGN KEY (`fk_reaction_area`) REFERENCES `area`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `area`.`token` ADD FOREIGN KEY (`fk_token_user`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;