package eu.epitech.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;

import java.util.ArrayList;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ActionView extends VerticalLayout implements View {
        private ArrayList<Button> actionsButton = new ArrayList<Button>();
        private int nbAction = 0;

        // Set in Action View the nbAction attribute by set it with the current nbAction we have
    public ActionView() {
        setSizeFull();
        setSpacing(true);
        for (int i = 0; i < nbAction; ++i) {
            actionsButton.add(actionButton("Description"));
        }
        for (Button button : actionsButton) {
            addComponent(button);
        }
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
        Notification.show("Welcome to action page !");
    }

    /*
    ** The String txt correspond to the name of the action. You can add a second parameters which will can be
    * the description of the action. In this case, append this parameters to 'txt' into the Button constructor.
     */
    private Button actionButton(String txt) {
        Button button = new Button(txt, new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                //txt is passing in parameters on the next view
                getUI().getNavigator().navigateTo("reaction" + "/" + txt);
            }
        });
        return button;
    }
}
