//* This Java source file was generated by the Gradle 'init' task.

import eu.epitech.area.*;
import org.junit.Test;
import static org.junit.Assert.*;

public class mainTest {
    @Test
    public void IsFiring() {
       assertTrue(1==1);
    }
}
